SemanticMediaWiki/SemanticScribunto

- src/ScribuntoLuaLibrary.php
- tests/phpunit/Unit/mw.ext.smw.results.tests.lua
> Change getQueryResult to avoid using API queries

- SemanticScribunto.php
> Check for minimum dependency using CONTENT_MODEL_SCRIBUNTO, refs #13

- docs/mw.smw.getQueryResult.md
- src/ScribuntoLuaLibrary.php
- tests/phpunit/Unit/ScribuntoLuaEngineTestBase.php
- tests/phpunit/Unit/ScribuntoLuaLibraryInfoTest.php
- tests/phpunit/Unit/ScribuntoLuaLibraryPropertyTest.php
- tests/phpunit/Unit/ScribuntoLuaLibraryResultsTest.php
- tests/phpunit/Unit/ScribuntoLuaLibrarySetTest.php
- tests/phpunit/Unit/ScribuntoLuaLibrarySubobjectTest.php
- tests/phpunit/Unit/ScribuntoLuaLibraryTest.php
- tests/phpunit/Unit/mw.smw.info.tests.lua
- tests/phpunit/Unit/mw.smw.set.tests.lua
- tests/phpunit/Unit/mw.smw.subobject.tests.lua
- tests/phpunit/Unit/mw.smw.tests.lua
in spirit of keeping one test class per method in ScribuntoLuaLibrary, I moved the php tests to their respective test classes.
> reorganized tests

- docs/README.md
- docs/mw.smw.ask.md
- src/LuaAskResultProcessor.php
- src/ScribuntoLuaLibrary.php
> fixes #25 (ask and getQueryResult fail on format=debug)

- composer.json
- docs/mw.smw.ask.md
- docs/mw.smw.set.md
- src/LibraryFactory.php
- tests/phpunit/Integration/JSONScript/Fixtures/module.smw.getQueryResult.lua
- tests/phpunit/Integration/JSONScript/Fixtures/module.smw.lua
- tests/phpunit/Integration/JSONScript/SemanticScribuntoJsonTestCaseScriptRunnerTest.php
- tests/phpunit/Integration/JSONScript/TestCases/ask-001.json
- tests/phpunit/Integration/JSONScript/TestCases/ask-002.json
- tests/phpunit/Integration/JSONScript/TestCases/ask-003.json
- tests/phpunit/Integration/JSONScript/TestCases/getQueryResult-001.json
- tests/phpunit/Integration/JSONScript/TestCases/getQueryResult-002.json
- tests/phpunit/Integration/JSONScript/TestCases/set-001.json
- tests/phpunit/Integration/JSONScript/TestCases/set-002.json
- tests/phpunit/Integration/JSONScript/TestCases/set-003.json
- tests/phpunit/Integration/JSONScript/TestCases/set-004.json
- tests/phpunit/Integration/JSONScript/TestCases/set-005.json
- tests/phpunit/Unit/LibraryFactoryTest.php
this adresses #7 and adds the necessary tests to check for correct result order
> closes #7 (integration tests for result order, functions ask and getQueryRsult)

- tests/phpunit/Integration/JSONScript/Fixtures/module.smw.lua
- tests/phpunit/Integration/JSONScript/TestCases/info-001.json
- tests/phpunit/Integration/JSONScript/TestCases/subobject-001.json
this containes some integration tests for the into and subobject functions.
> added integration tests for mw.smw.info and mw.smw.subobject

- tests/phpunit/Integration/JSONScript/TestCases/subobject-001.json
also: cleaned-up my leftovers in subobject-001.json
> bumped version to 1.0

- RELEASE-NOTES.md
- SemanticScribunto.php
- composer.json
Make the 1.0.0 release. Refs https://github.com/SemanticMediaWiki/SemanticScribunto/issues/11
Add release date
> Make the 1.0.0 release

- README.md
- RELEASE-NOTES.md
- SemanticScribunto.php
- composer.json
Refs: https://github.com/SemanticMediaWiki/SemanticScribunto/issues/42
> 1.1.0 release

- tests/phpunit/Integration/JSONScript/Fixtures/module.smw.getQueryResult.lua
- tests/phpunit/Integration/JSONScript/Fixtures/module.smw.lua
- tests/phpunit/Integration/JSONScript/SemanticScribuntoJsonTestCaseScriptRunnerTest.php
- tests/phpunit/Integration/JSONScript/TestCases/ask-001.json
also: removed unused code in fixture
> fix #50 (failing ask tests due to changes in mw master)

- RELEASE-NOTES.md
- SemanticScribunto.php
- composer.json
Make the 1.1.1 release
* Provide information about the release
* Bump version to the release
> 1.1.1 release

- docs/mw.smw.set.md
- docs/mw.smw.subobject.md
- src/ScribuntoLuaLibrary.php
- tests/phpunit/Integration/JSONScript/Fixtures/module.i55.lua
- tests/phpunit/Integration/JSONScript/TestCases/set-007.json
- tests/phpunit/Integration/JSONScript/TestCases/subobject-002.json
> add feature #55: set and subobject can take property values from subtables

- SemanticScribunto.php
- tests/bootstrap.php
- tests/phpunit/Integration/JSONScript/SemanticScribuntoJsonTestCaseScriptRunnerTest.php
This PR is made in reference to: #30, https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4197
Fixes #30
> Use `LightweightJsonTestCaseScriptRunner`, refs 30

- .travis.yml
This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4209
> [CI] Enable SQLite

- README.md
- RELEASE-NOTES.md
- composer.json
- extension.json
This PR is made in reference to: #68 
- Updated release notes
- Updated readme
- Updated meta files
Fixes #
> Make 2.1.0 release

- composer.json
- extension.json
This PR is made in reference to: #68 
- Update meta files for 2.2.0-alpha
Fixes #
> Start 2.2.0 development

- composer.json
This PR is made in reference to: https://github.com/SemanticMediaWiki/SemanticScribunto/issues/77#issuecomment-1015796985
- Also allow SMW 4.0
Fixes #
> Also allow SMW 4.0

- .travis.yml
- README.md
- RELEASE-NOTES.md
- composer.json
- extension.json
This PR is made in reference to: #77 
- Updated release notes
- Updated readme
- Bumps requirements
- Bumps versions
Fixes #
> Make 2.2.0 release

- composer.json
- extension.json
This PR is made in reference to: #77 
- Starts 2.3.0
Fixes #77
> Start developing 2.3.0

- composer.json
> Allow SMW 5.X in composer.json
